### ISSUE TITLE
only works on linux?

### ISSUE THREAD

**Issue by alepore** [KELiON/gemsource#1]
i think your command `bundle show | cut -d \" \" -f 4 | sed 1d` only works on linux.
i tried on OSX and i get no output, probably because `cut` or `sed` works in a different way.

an alternative could be:
`bundle show | sed -E 's/(  \* |\(.*\)|Gems.*)//g'`

but it's probably better to do that at code level...

Cheers!

**Comment by alepore** [comment]
nevermind.. now works (?)

**Comment by KELiON** [comment]
@alepore I just removed usage of `cut` and `sed`, now it only uses `cd` and `bundle show` so that should work on mac/linux/windows. Btw I tested it on OSx and first version worked for me
