### ISSUE TITLE
No gems are listed

### ISSUE THREAD

**Issue by meleyal** [KELiON/gemsource#4]
It was working previously but since some Atom updates gems are no longer listed, the dialog is blank.

I've tried it in several Rails projects with the same result, using Atom 1.0.6.

**Comment by KELiON** [comment]
@meleyal looks like it is not related to updates. I just tried it on Atom 1.0.7 and it works fine. Could you open developer console in atom (views -> developer -> toggle developer console) and check if there are any exceptions when you try to use this plugin?

**Comment by Rikkitp** [comment]
I don't have any exceptions (in developer console) and no gems are listed.
Atom 1.2.0 beta

**Comment by KELiON** [comment]
@Rikkitp @meleyal now I see the issue, will fix it, thanks!

**Comment by wielinde** [comment]
@KELiON Just found your plugin and ran into the same problem as the others. Any updates planned?

**Comment by ganesharulanantham** [comment]
@wielinde  and @KELiON  When I tried to run this package in development mode It works fine! But in normal mode gem list does not get loaded. 
I found this exception when this package run in normal mode.

```
Error: Command failed: /bin/sh -c cd /Users/user/Desktop/work/app && bundle show
/bin/sh: bundle: command not found

    at ChildProcess.exithandler (child_process.js:215:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

Why bundle command not found in normal mode? Any idea
